print('B站BV号转换为AV号转换器 - GamerNoTitle')
print('-------------------------------------')
bv=input('请输入BV号：')
withoutbv=str(bv).strip('BV')
num=[]
minus=100618342136696320
or_num=177451812
# for i in range(len(withoutbv)):
# 	int num[i]=0
for index in range(len(withoutbv)):	# 遍历字符串获取BV号并附对应的值
	temp=withoutbv[index]
	if(temp=='1'): num.append(13)
	elif(temp=='2'): num.append(12)
	elif(temp=='3'): num.append(46)
	elif(temp=='4'): num.append(31)
	elif(temp=='5'): num.append(43)
	elif(temp=='6'): num.append(18)
	elif(temp=='7'): num.append(40)
	elif(temp=='8'): num.append(28)
	elif(temp=='9'): num.append(5)
	elif(temp=='A'): num.append(54)
	elif(temp=='B'): num.append(20)
	elif(temp=='C'): num.append(15)
	elif(temp=='D'): num.append(8)
	elif(temp=='E'): num.append(39)
	elif(temp=='F'): num.append(57)
	elif(temp=='G'): num.append(45)
	elif(temp=='H'): num.append(36)
	elif(temp=='J'): num.append(38)
	elif(temp=='K'): num.append(51)
	elif(temp=='L'): num.append(42)
	elif(temp=='M'): num.append(49)
	elif(temp=='N'): num.append(52)
	elif(temp=='P'): num.append(53)
	elif(temp=='Q'): num.append(7)
	elif(temp=='R'): num.append(4)
	elif(temp=='S'): num.append(9)
	elif(temp=='T'): num.append(50)
	elif(temp=='U'): num.append(10)
	elif(temp=='V'): num.append(44)
	elif(temp=='W'): num.append(34)
	elif(temp=='X'): num.append(6)
	elif(temp=='Y'): num.append(25)
	elif(temp=='Z'): num.append(1)
	elif(temp=='a'): num.append(26)
	elif(temp=='b'): num.append(29)
	elif(temp=='c'): num.append(56)
	elif(temp=='d'): num.append(3)
	elif(temp=='e'): num.append(24)
	elif(temp=='f'): num.append(0)
	elif(temp=='g'): num.append(47)
	elif(temp=='h'): num.append(27)
	elif(temp=='u'): num.append(22)
	elif(temp=='j'): num.append(41)
	elif(temp=='k'): num.append(16)
	elif(temp=='m'): num.append(11)
	elif(temp=='n'): num.append(37)
	elif(temp=='o'): num.append(2)
	elif(temp=='p'): num.append(35)
	elif(temp=='q'): num.append(21)
	elif(temp=='r'): num.append(17)
	elif(temp=='s'): num.append(33)
	elif(temp=='t'): num.append(30)
	elif(temp=='u'): num.append(48)
	elif(temp=='v'): num.append(23)
	elif(temp=='w'): num.append(55)
	elif(temp=='x'): num.append(32)
	elif(temp=='y'): num.append(14)
	elif(temp=='z'): num.append(19)
total=num[0]*58**6+num[1]*58**2+num[2]*58**4+num[3]*58**8+num[4]*58**5+num[5]*58**9+num[6]*58**3+num[7]*58**7+num[8]*58+num[9]	# 将获取到的值相加
total_minus=total-minus	# 与固定值相减
b0=bin(total_minus)
without_0b=str(b0).strip('0b')	# 去掉二进制头部的'0b'
a=int(without_0b,2)
b=or_num
result_bin=a ^ b	# 进行异或运算
print('该视频的AV号是AV{}'.format(result_bin))